# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - AzureTerm2v5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Switch to Ubuntu for compatibility with CI=false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Running npm install, and skipping test temporarily
      - name: npm install, build, and test
        working-directory: ./plantcareappProject/plantcareapp
        run: |
          CI=false npm install
          CI=false npm run build --if-present
          # Skipping tests for now
          # npm run test --if-present
      
      - name: Upload artifact for deployment job  # Corrected indentation here
        uses: actions/upload-artifact@v4
        with:
            name: node-app
            path: ./plantcareappProject/plantcareapp/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'AzureTerm2v5'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_98D49EC011124BBC8209C36685CBFDB6 }}
